version: '3.8'

services:
  backend:
    container_name: backend
    image: saurabhshinde27/backend-repo:latest
    env_file: ./todo-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - todo-network

  frontend:
    container_name: frontend
    image: saurabhshinde27/frontend-repo:latest
    env_file: ./todo-fronted/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - todo-network

volumes:
  mongo_data:

networks:
  todo-network:
    driver: bridge
